# Generated by Django 4.2.7 on 2024-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Legal Expert'), (2, 'Editor'), (3, 'Manager')], null=True),
        ),
    ]
