# Generated by Django 4.2.7 on 2024-03-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openaichatresponse',
            old_name='response',
            new_name='summary',
        ),
    ]
