# Generated by Django 4.2.7 on 2024-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_rename_response_openaichatresponse_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGptBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageInput', models.TextField()),
                ('bot_response', models.TextField()),
            ],
        ),
    ]
